[Feature/PE1-26] Learn git terminal
poly-team/poly_events_mobile pull request #12
Opened 2021-06-19 14:54 UTC by JaedonC

2021-06-19 15:00 UTC, Sheldonsu28 approved these changes, later dismissed

2021-06-20 02:25 UTC, lanyanxiang requested changes
Thanks for contributing.

A few questions:
* `Poly Events Design/PEhomepageImage.png` seems to belong to the `assets` folder created by Frank. @shoko-inori can you look at this?
* Can you rename the design folder to use all lower-case letters so that its naming matches other folders?
* This is related to the ongoing research being conducted by Frank. @shoko-inori Do you mind assisting Jaedon to name these images according to your research after you complete it? For example, I was thinking instead of naming files `PEhomepage1.png` and `PEhomepage2.png`, it might be better to name them something like `home_active_no_event.png` and `home_active_with_events.png`. It will be nice if @shoko-inori and @JaedonC can have a discussion about the naming rules.
* It's great to see that we have a better pull request title (and branch title). However, although it describes that Jaedon is learning terminal git, it does not tell us what is changed in this branch. Can we rename this pull request to "Add organization home design images", or any other name that describes the changes?

Some follow-up questions:
@Sheldonsu28 Did we discuss with Jaedon on this design? For example, I didn't see the search feature on the spec. If we need this feature, let's bring it up during the internal meeting and add it to the spec.

Thanks for your care! Congratulations on performing your first commits using terminal git @JaedonC.

2021-06-24 16:10 UTC, lanyanxiang approved these changes
Looks good to me! Thanks Jaedon for taking care of this. We need your inputs as follow-ups. See above @shoko-inori.

2021-06-24 16:13 UTC, Sheldonsu28 approved these changes

2021-06-24 16:13 UTC, merged